# Generated by Django 5.1.13 on 2025-11-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad_estimada', models.IntegerField(blank=True, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='appexamen.centro')),
                ('vacunas', models.ManyToManyField(related_name='animal_vacunas', to='appexamen.vacuna')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='appexamen.refugio'),
        ),
        migrations.CreateModel(
            name='Revision_Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_salud', models.IntegerField()),
                ('fecha', models.DateField()),
                ('veterinario', models.CharField(max_length=150)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='appexamen.animal')),
            ],
        ),
    ]
