# Generated by Django 5.1.13 on 2025-11-04 10:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('play', 'Play Station'), ('xbox', 'Xbox')], max_length=100)),
                ('fabricante', models.CharField(choices=[('sony', 'Sony'), ('ea', 'Electronic Arts')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('SP', 'España'), ('EEUU', 'Estados Unidos')], max_length=50)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estudio_sede', to='appexamen.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('ventas_estimadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estudio_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appexamen.estudio')),
                ('plataforma', models.ManyToManyField(related_name='videojuego_plataformas', to='appexamen.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisisDeVideojuego', to='appexamen.videojuego')),
            ],
        ),
    ]
