# Generated by Django 5.1.13 on 2025-11-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexamen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vacunas',
            field=models.ManyToManyField(related_name='animal_vacunas', to='appexamen.vacuna'),
        ),
    ]
