# Generated by Django 5.1.13 on 2025-11-04 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexamen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='estudio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudio_sede', to='appexamen.estudio'),
        ),
    ]
